### ISSUE TITLE
update picasso

### ISSUE THREAD

**Issue by croccio** [JoanZapata/base-adapter-helper#46]
please update picasso i get this error

Process: com.paybay.quipromotionapi, PID: 17261
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/okhttp/HttpResponseCache;
            at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:74)
            at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:51)
            at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:41)
            at com.squareup.picasso.Utils$OkHttpLoaderCreator.create(Utils.java:231)
            at com.squareup.picasso.Utils.createDefaultDownloader(Utils.java:146)
            at com.squareup.picasso.Picasso$Builder.build(Picasso.java:490)
            at com.squareup.picasso.Picasso.with(Picasso.java:390)
            at com.joanzapata.android.BaseAdapterHelper.setImageUrl(BaseAdapterHelper.java:200)
            at com.paybay.quipromotionapi.PromotionListActivity$1.convert(PromotionListActivity.java:25)
            at com.paybay.quipromotionapi.PromotionListActivity$1.convert(PromotionListActivity.java:22)
            at com.joanzapata.android.BaseQuickAdapter.getView(BaseQuickAdapter.java:102)
            at android.widget.AbsListView.obtainView(AbsListView.java:2344)
            at android.widget.ListView.makeAndAddView(ListView.java:1864)
            at android.widget.ListView.fillDown(ListView.java:698)
            at android.widget.ListView.fillFromTop(ListView.java:759)
            at android.widget.ListView.layoutChildren(ListView.java:1659)
            at android.widget.AbsListView.onLayout(AbsListView.java:2148)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:502)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2072)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1829)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.squareup.okhttp.HttpResponseC

I'm my grade i've 

    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.0.0'
    compile 'com.squareup.okhttp:okhttp:2.0.0'

but app crash

**Comment by croccio** [comment]
i solved putting new picasso library and set transitive property on your library, you can close. Thank u
